In [17]:
import numpy as np

#Read in the example and real inputs:
with open('AoC13example.txt') as input:
    lines = input.readlines()
with open('AoC13.txt') as input1:
    real_lines = input1.readlines()
    
#Function to read the instructions to create the grid which will be folded:
#Inputs are the full puzzle input (instruction_lines) and a number of lines at the bottom to discard (as they are folding instructions) 
def createGrid(instruction_lines, discard):
    
    #Put the coordinate values in a nump array
    coords = np.zeros((len(instruction_lines) - discard,2))
    print(len(instruction_lines))
    for j in range(len(instruction_lines) - (discard)):
        for i in range(2):
            coords[j,i] = instruction_lines[j].rstrip().split(',')[i]
    
    #Find the dimensions of the grid
    max_x = int(max(coords[:,0]))
    max_y = int(max(coords[:,1]))
    
    #Create an empty grid of zeros
    gr = np.zeros((max_y+1,max_x+1))
    
    #Now add the ones according to the instructions
    for j in range(len(coords)):
        gr[int(coords[j][1]),int(coords[j][0])] += 1
    
    return gr
    
#Function to read the instructions (puzzle input) and return two lists containing the directions and positions of the lines along which to fold
#Takes the full list of instructions and the number of lines which contain folding instructions (n) 
def parseDirections(instruction_lines,n):
    #maybe take last few characters from the n last lines
    shortlist = instruction_lines[-n:]
    
    dirs = []
    ints = []
    for i in shortlist:
        dirs.append(i.split(' ')[2].split('=')[0])
        ints.append(int(i.split(' ')[2].split('=')[1]))
        
    #We now have a list of the directions and positions of the foldlines
    return dirs, ints

#Function to apply a fold along a horizontal line (y=n) to a given grid:
#Takes the input grid (gr), its dimensions (x0,y0) and the line along which to fold (foldline)
def horfold(gr,x0,y0,foldline):
    
    #Initialise an empty additions array:
    additions = np.zeros((int((y0-1)/2)+1,x0))  
    
    #For any non-zero point on the bottom half of the input grid, we add the corresponding mirror image point to the additions array
    for j in range(x0):
        for i in range(y0):
            if (i > foldline) and (gr[i,j] == 1):
                #Find the distance from the foldline:
                over = i - foldline
                new_y = foldline - over
                
                #Change the mirror image point to a one in the additions array
                additions[new_y,j] += 1
    
    #Now take just the top half of the original grid and add it to additions array
    for i in range(foldline):
        additions[i,:] += gr[i,:]
    
    #Finally reset everything non-zero to one:
    for i in range(foldline):
        for j in range(x0):
            if additions[i,j] > 0:
                additions[i,j] = 1
    
    #Finally we need to count the number of ones in the resulting grid
    tempcnt = 0
    for j in range(foldline):
        for i in range(x0):
            if additions[j,i] == 1:
                tempcnt += 1
    
    return additions, tempcnt
    
#Function to apply a fold along a vertical line (x=n) to a given grid:
#Takes the input grid (gr), its dimensions (x0,y0) and the line along which to fold (foldline)
def verfold(gr,x0,y0,foldline):
    
    #Initialise an empty additions array (half the area of the grid to be folded):
    additions = np.zeros((y0, int((x0-1)/2)))
    
    #For any non-zero point on the right half of the input grid, we add the corresponding mirror image point to the additions array
    for j in range(int(x0)):
        for i in range(int(y0)):
            if (j > foldline) and (gr[i,j] == 1):
                #Find the distance from the foldline:
                over = j - foldline
                new_x = foldline - over
                
                #Change the mirror image point to a one in the additions array
                additions[i,new_x] += 1
    
    #Now take just the left half of the original grid and add it to additions
    for j in range(foldline):
        additions[:,j] += gr[:,j]
    
    #Finally reset everything non-zero to one:
    for i in range(foldline):
        for j in range(y0):
            if additions[j,i] > 0:
                additions[j,i] = 1
                
    #Finally we need to count the number of ones in the resulting grid
    tempcnt = 0
    for j in range(foldline):
        for i in range(y0):
            if additions[i,j] == 1:
                tempcnt += 1
    
    return additions, tempcnt
    
    
#In the example input there are 3 lines to discard in the creation of the grid, 13 for the real input
grid = createGrid(lines, 3)
print("The example grid:")
print(grid)

#The parsed folding instructions
parsed = parseDirections(lines,2)
print("Folding instructions for the example input:")
print(parsed)

#Fold the example input:
print("After the first fold:")
grid = horfold(grid,11,14,7)[0]
print(grid)

print("After the next fold:")
grid = verfold(grid,11,7,5)[0]
print(grid)

#Now for the real input, to get the first puzzle answer:
grid2 = createGrid(real_lines, 13)
#Only need to return the count of the ones in the grid (second element in the tuple returned by the function)
count = verfold(grid2, 1311, 894, 655)[1]
print("There are " + str(count) + " dots (ones) visible on the paper after the first fold")



21
The example grid:
[[0. 0. 0. 1. 0. 0. 1. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 1. 0. 1. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Folding instructions for the example input:
(['y', 'x'], [7, 5])
After the first fold:
[[0. 0. 0. 1. 0. 0. 1. 0. 0. 1. 0.]
 [1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0. 1. 0. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
After the next fold:
[[0. 1. 0. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 